### ISSUE TITLE
Portability

### ISSUE THREAD

**Issue by bacaa0** [OV2/RapidCRC-Unicode#10]
Add button install/uninstall shell extension for making rapidcrc portable

**Comment by redactedscribe** [comment]
Hello @OV2.

I've tried to register the shell extension during installation via Scoop (manifest PR https://github.com/ScoopInstaller/Extras/pull/16246) however stupidly I forgot to actually test whether the registration of rcrcshex.dll / rcrcshex64.dll actually worked. It registers correctly, but the shell extension doesn't work.

Do you have any ideas? Something is missing. The RapidCRC context menu item does appear, but all of its menu items give:

```
---------------------------
Error Message
---------------------------
Error opening exe path from registry:

The operation completed successfully.


---------------------------
OK   
---------------------------
```

Testing locally on Windows 11 I'm doing:

- Reg: `C:\WINDOWS\System32\regsvr32 "D:\!S\apps\rapidcrc\0.3.41\rcrcshex64.dll"`
- Unreg: `C:\WINDOWS\System32\regsvr32 /u "D:\!S\apps\rapidcrc\0.3.41\rcrcshex64.dll"`

`Computer\HKEY_CLASSES_ROOT\*\shellex\ContextMenuHandlers\RCRCFile64\(Default)` points to `{625FC2A0-B157-4574-928F-C06F3BC1B127}`, and `Computer\HKEY_CLASSES_ROOT\CLSID\{625FC2A0-B157-4574-928F-C06F3BC1B127}\InprocServer32\(Default)` correctly points to `D:\!S\apps\rapidcrc\0.3.41\rcrcshex64.dll`.

Any help is appreciated, thanks.

**Comment by OV2** [comment]
The shell extension requires the registry key
```
HKEY_LOCAL_MACHINE\SOFTWARE\Microsoft\Windows\CurrentVersion\App Paths\rapidcrc.exe
```
with the default entry set to the location of rapidcrc.exe

**Comment by redactedscribe** [comment]
Perfect! That was the missing piece. Much appreciated.

**Comment by redactedscribe** [comment]
@OV2 Feel free to check out the manifest edit and leave a comment if you agree. It could help it get merged sooner. Thanks again for your help.
