### ISSUE TITLE
Issue with UNC paths crashing RapidCRC when using "Remove from list"

### ISSUE THREAD

**Issue by hurda** [OV2/RapidCRC-Unicode#18]
RapidCRC 0.3.15 x64
Windows 7 SP1 64bit

Steps to reproduce:
- Search for anything in Windows' Search (winkey+f)
- Select two files, preferably small ones, from different directories and open them with RapidCRC by using the context menu. They should be added and displayed with UNC-paths.
- After the checksum-calculation is finished, remove one of the files from the list with the context-menu.
- Click "SFV File" and select "one sfv-file for all files"
- Browse to a folder, choose a name and save the file

Expected result:
The sfv-file is saved.

Actual result:
First an error-dialog pops up:
![rapidcrc1](https://cloud.githubusercontent.com/assets/3539609/4176066/84270e4c-35f2-11e4-9109-69a46f3ebb29.png)

After clicking OK, the program crashes:
```
Problem signature:
  Problem Event Name:	APPCRASH
  Application Name:	RapidCRC.exe
  Application Version:	0.3.15.0
  Application Timestamp:	53f88884
  Fault Module Name:	RapidCRC.exe
  Fault Module Version:	0.3.15.0
  Fault Module Timestamp:	53f88884
  Exception Code:	40000015
  Exception Offset:	000000000002a9d2
  OS Version:	6.1.7601.2.1.0.256.1
  Locale ID:	3079
  Additional Information 1:	98e1
  Additional Information 2:	98e185bb698dbbeb81cf31137ed88d60
  Additional Information 3:	45f8
  Additional Information 4:	45f82661a91a3c506b8fcf41ccaa1b7d

Read our privacy statement online:
  http://go.microsoft.com/fwlink/?linkid=104288&clcid=0x0409

If the online privacy statement is not available, please read our privacy statement offline:
  C:\Windows\system32\en-US\erofflps.txt
```

**Comment by sergeevabc** [comment]
Let’s say test.sha1 contains the following record with [UNC-path][1]:
```53c06893b7eeada6ac3acb7a33f1a0ee2029d6d2 \\?\D:\s o m e l o n g p a t h\test.zip```
Then RapidCRC 0.3.23 fails to validate and throws error in Info column. Why? SFVNinja validates its fine.

[1]: https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path

**Comment by OV2** [comment]
That is an extended-length path, which is really only supposed to be used internally. RapidCRC will automatically access files with this prefix, so if you remove it from your hash file it should work.
Writing the prefix to hash files makes them unusable in programs that do not understand it, so RCRC will never write it to the hash files.
I will add some code that automatically removes it when reading a hash file.

Please open a new issue in the future - if you want to reference an older issue just mention it with #NUMBER
