### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by kostasall12** [OV2/RapidCRC-Unicode#194]
Is it possible to right-click on a folder and have the option "Verify checksums", where that option will scan the directory and immediately verify any hash files contained within?

**Comment by OV2** [comment]
You can already do that by selecting "RapidCRC->Open all hash files" in the shell extension.

**Comment by kostasall12** [comment]
This option "RapidCRC->Open all hashes" shows me the files from the first hash it finds inside the folder, is there a way to show me all the files from all hashes inside the folder, including subfolders?

![test](https://github.com/OV2/RapidCRC-Unicode/assets/79175031/11335825-bdcb-489b-9d33-3de87711d0f9)

**Comment by OV2** [comment]
To have multiple jobs in the GUI at the same time you need to enable "Enable Job Queueing" in the options.

**Comment by kostasall12** [comment]
Thank you!!!
