### ISSUE TITLE
force open as a regular file in case calling hashing by hash type

### ISSUE THREAD

**Issue by gppdee2p** [OV2/RapidCRC-Unicode#197]
Hello, OV2!

I get unexpected SW behavior.
If I call SHA256 function from menu and the list to be hashed containes SHA256 file that comes fist in the list it runs verification instead of calculation.
Calling SHA256 from a context menu a user would expect always hash calculation even if the list containes SHA256 files.

Thank you for considering the request.

BR
Andriy

**Comment by OV2** [comment]
It's not really a useful use-case, but you're right - in this case it does not make sense to interpret the hash file.

**Comment by gppdee2p** [comment]
> It's not really a useful use-case, but you're right - in this case it does not make sense to interpret the hash file.

OV2, when are you planning to issue a new release?

**Comment by OV2** [comment]
I hoped to maybe do some additional work, but could not find the time. So I've made a small release with this fix included.
