### ISSUE TITLE
Which file failed? How can one tell?

### ISSUE THREAD

**Issue by zakimohzani** [OV2/RapidCRC-Unicode#201]
I chose the option where a checksum.sfv file is saved into every directory. And then, I injected a corruption into one of the files. 

![image](https://github.com/OV2/RapidCRC-Unicode/assets/18021169/1a196183-5db5-48d6-afa1-f35431db4d70)

So RapidCRC does detect it but I can't tell which file failed. How can I see this? Is it written somewhere in the logs?

**Comment by OV2** [comment]
In the mode you are using the gui can only ever display one job at a time. So if you open multiple sfv files only the last one will be displayed. If you enable job queueing in the options, all jobs will be displayed.
