### ISSUE TITLE
(Question or possible feature request) verifying files in subfolders.

### ISSUE THREAD

**Issue by TomTurbine** [OV2/RapidCRC-Unicode#203]
Wanting to verify files, all of them are present and included in the md5 files, but like to keep them separated into subfolders to keep things organized. Is it possible to have RapidCRC-Unicode to scan the folder it starts in and all subfolders recursively in it to verify an MD5 file?

Bonus if it can also show any extra files it finds that aren't listed in the MD5 file.

**Comment by OV2** [comment]
If you mean that you have one md5 file, and the files it references are not in the location it expects, then no, there is no auto search for referenced files.

If you just want to recursively verify all md5 files in a folder, then that is an option in the shell extension as well as in the open files dialog (in the dropdown arrow  of the open button).

**Comment by TomTurbine** [comment]
Lets say its like this.

Root Folder
>MD5 File
>File 1
>Subfolder 1
>>File 2
>>File 3
>>Subfolder 2
>>>>File 4
>>>>File 5


All the files are within that main folder, just within possible subdirectories within it.

**Comment by OV2** [comment]
If you create the md5 file with that structure present it will work. In this case the md5 file references the files including their folders.

**Comment by TomTurbine** [comment]
Thank you sir, was hoping there was a way to do that automatically and just treat all subfolders as part of the same directory. Oh well, either way, thanks for the program, works great and love that it's portable
