### ISSUE TITLE
Confusing status when adding files via shell extension

### ISSUE THREAD

**Issue by mohas** [OV2/RapidCRC-Unicode#22]
When you select put CRC in file name with shell extension for more than 1 file, the status for files that are added to list becomes "no hash found" which is rather confusing, this behavior is different when adding only one file for processing.

![capture](https://cloud.githubusercontent.com/assets/1816728/4341908/96932d1c-403e-11e4-99ce-e9d9c7d23192.PNG)

**Comment by c1b8c1-star** [comment]
Shell extension don't show in v0.3.41 in Windows 11.

Thank

**Comment by c1b8c1-star** [comment]
Shell extension don't show in v0.3.41 in Windows 11.

Thank

**Comment by OV2** [comment]
You need to click on "Show more options" to get to the old style explorer context menu.

**Comment by c1b8c1-star** [comment]
"Show more options", yes i know but there isn't (Windows 11 25H2 x64 build 26200.8894).

**Comment by c1b8c1-star** [comment]
I found 
https://www.turbosfv.com/ 
which works well, thanks anyway.

**Comment by c1b8c1-star** [comment]
Now he's back, mystery.
Thank.
