### ISSUE TITLE
Certain file names not properly registered when loading from SFV file

### ISSUE THREAD

**Issue by biosquid2** [OV2/RapidCRC-Unicode#24]
Rename any file as "+-.extension"; e.g. "Test+-.txt". Create a SFV file from that particular file. The SFV file is generated properly. However, load up the SFV file and RapidCRC Unicode will only display "Test+.txt" as the file name, while listing only the Info as File not found. I have not tested other symbols or combinations. Also, the original RapidCRC does not exhibit this. Likely an issue with the recursive algorithm for sifting through file names.

![untitled](https://cloud.githubusercontent.com/assets/10481097/5693803/338d06e4-98fd-11e4-96de-c6f8c220a80b.png)

![untitled2](https://cloud.githubusercontent.com/assets/10481097/5693806/3d8e6cd2-98fd-11e4-9f1f-f4f2d574dc3e.png)

**Comment by OV2** [comment]
This is a problem with the codepage detection. Since the file contains only a few characters, the windows function to determine the file codepage "guesses" wrong, and thus you get wrong filenames.

You can either force utf-8 via the options, or chose one of the other unicode types for hash file creation.

**Comment by c9870** [comment]
thanks @biosquid2 @OV2 
had a problem were there was the "TM" character in the file names of a few files which was causing errors.  

setting in the options 
in 'File Creation' section
checking "Create Unicode Files"
setting Drop down to the right of that to "UTF - 8 with DOM" or "UTF - 16 LE" fixed the problem

picture before i fixed the problem
![fail](https://cloud.githubusercontent.com/assets/12579538/7786429/292a005c-0195-11e5-882c-e8341b5a7ba8.JPG)
