### ISSUE TITLE
Bug Unable to Handle Certain Unicode Character

### ISSUE THREAD

**Issue by TimidScript** [OV2/RapidCRC-Unicode#26]
A file with the following name cannot be processed: "A Warrior’s_Heart"

The image shows the error I get. It seems it cannot handle the special apostrophe (Single right quotation). 

<code>’	right single quotation mark	020031	8217	0x2019	&rsquo;</code>

![099](https://cloud.githubusercontent.com/assets/8114076/6783671/08055978-d173-11e4-996b-31a07d769d79.png)

**Comment by OV2** [comment]
Is this when opening a hash file, or when dropping a file onto rcrc? For opening a hash file take a look at issue https://github.com/OV2/RapidCRC-Unicode/issues/24

**Comment by TimidScript** [comment]
It's opening. Forcing UTF8 fixes the issue. Thank you.
