### ISSUE TITLE
Not much of an issue but...

### ISSUE THREAD

**Issue by bejita7** [OV2/RapidCRC-Unicode#28]
there's something off in the interface. When I open RCR it looks like this (D2K instead of ED2K):
![r1](https://cloud.githubusercontent.com/assets/2895218/10972313/ebbedf28-83d8-11e5-922d-345ce4730a22.PNG)

Than, when i minimize and maximize it looks normal again:
![r2](https://cloud.githubusercontent.com/assets/2895218/10972340/02ecd006-83d9-11e5-965b-60cfeeddbd60.PNG)

Yeah, screenshots from Win XP but it's also happening in home PC with Win 10.

**Comment by OV2** [comment]
Should be fixed in 0.3.18
