### ISSUE TITLE
"Clear List" and "Remove Selected Items" Grayed Out in All Circumstances

### ISSUE THREAD

**Issue by biosquid2** [OV2/RapidCRC-Unicode#29]
The "Clear List" and "Remove Selected Items" options in the ListView context menu are perpetually grayed out in the latest build, v0.3.17. Currently, the only way to clear the list with job queuing enabled is to restart the application. Also, the options to copy certain SHA3 hashes as well as ED2K to Clipboard are always available in said context menu, despite NOT having the application calculate those. Again, all these issues were introduced in v0.3.17--prior versions perform as expected.

**Comment by OV2** [comment]
Should be fixed in 0.3.18
