### ISSUE TITLE
Option to switch between relative and absolute path

### ISSUE THREAD

**Issue by MrDito** [OV2/RapidCRC-Unicode#31]
It would be a very useful option if you could switch between the files' absolute and the relative path saved in a hash file.
By this, there would be the possibility to check files integrity by a hash file which has not necessarily placed relative to the hashed files.
Furthermore you could merge multiple hash files to a combined one (maybe another feature ;-) ) and so quickly update a overall hash file for all files on the disk by just updateing a single folders hash file and merge again to a new overall hash file, instead of a complete new calculation.

**Comment by konstanz** [comment]
Ideally, for absolute path a switch to select with or without volume drive letter (for windows).
I mean, you can choose between
D:\ABC\test.txt 54EA710A
and
ABC\test.txt 54EA710A
But if no such switch is wished/possible, in case of doubt without volume drive letter would be to prefer (for platform independence (linux, ...))

**Comment by OV2** [comment]
I've added an option for absolute paths in 0.3.20 (756f14d). For now it saves absolute paths with drive letter. It doesn't really make sense for cross platform, since the absolute path would seldom be the same.
