### ISSUE TITLE
Check CRC with absolute paths

### ISSUE THREAD

**Issue by LonerD** [OV2/RapidCRC-Unicode#35]
Some programs create CRC with absolute paths.
But RapidCRC can't check it. For example, md5 file can contains:
f2107ca3a1bd7d398150d3623b565a62  C:\MyDirectory\MyFile.rar
Please, add possibility to check such files (and it would be great if RapidCRC can create such files too)

**Comment by OV2** [comment]
This seems to be a bug introduced with the support for long path names, I'll fix it. Creating with absolute paths is a bit more work, I'll see if I can find the time.

**Comment by OV2** [comment]
Should be fixed in 756f14d (0.3.20)
