### ISSUE TITLE
Feature request: batch-remove CRC characters

### ISSUE THREAD

**Issue by vatterspun** [OV2/RapidCRC-Unicode#38]
**Current behavior**: program can add CRC characters to a file name, but no functionality exists to remove that text for example if a user wants to switch to a more reliable and secure hashing mechanism like SHA1 or others.

**Requested behavior**: capability to remove all CRC characters e.g. File [8D2JKSIR].avi -> File.avi

**Workaround**: use a program like [Ant Renamer](http://www.antp.be/software/renamer) (open source freeware) with the following settings:
1. Select the _Characters Deletion_ tab
2. Set _Number of characters to delete: 11_
3. Select, _From position: 0, From end_ 

View of this config: https://i.imgur.com/ib9Oo3m.png

**Comment by Silvernine0S** [comment]
Thanks for the tips! However, it's better to use the **Regular expression** in Ant Renamer with the following **Expression: (\s|_)(\[|\()[0-f]{8}(\]|\))**. At least with this, it won't randomly strip any 11 characters and will only specifically target the CRC32 checksum.

**Comment by vatterspun** [comment]
> it's better to use the Regular expression in Ant Renamer

I will test that out, thanks!

**Comment by vatterspun** [comment]
Both due to age and the suggestion that it was probably out of scope when I posted it, I'll go ahead and close.  I think the solution offered by @Silvernine0S is more than adequate.

**Comment by Zuescho** [comment]
Old comment but wanted to provide my own regex for this problem, because i found this answer on google.
Use this

`(\s||_)(\[|\()[a-fA-F0-9]{8}(]|\))`

with https://www.advancedrenamer.com/
