### ISSUE TITLE
"CRC into Filename" for files without extension creates invalid file name in Win32 name space

### ISSUE THREAD

**Issue by danielmmmm** [OV2/RapidCRC-Unicode#39]
When adding a CRC into the filename of files without an extension, RapidCRC will not only add the CRC into the filename but also add a trailing dot. This creates an invalid filename in Win32 name space. Such a file can only be deleted with "\\?\" syntax in the command line.

Example:

Create an empty file with filename "test"
Calculate the CRC and click "CRC into Filename" => RapidCRC will rename the file to "test [00000000]."
This file cannot be deleted with Windows File Explorer or "del "test [00000000]."". It can only be deleted with "del "\\?\C:\test [00000000]."".

**Comment by danielmmmm** [comment]
Sorry for not replying earlier. I tested version 0.3.22 and it works flawlessly.
Thank you very much!

**Comment by OV2** [comment]
No problem, and thanks for the feedback.
