### ISSUE TITLE
[PENDING] Essential: add Stop button

### ISSUE THREAD

**Issue by sergeevabc** [OV2/RapidCRC-Unicode#40]
The only way to cancel processing is to close RapidCRC Unicode. Alas, losing all intermediate data.
Could you be so kind to add Abort or Cancel or Stop button? Check how other solutions approach it.

[**MultiHasher**](http://www.abelhadigital.com/multihasher)
![3]

[**SVF Ninja**](http://skwire.dcmembers.com/fp/?page=sfv-ninja)
![2]

[**FileVerifier++**](http://www.programmingunlimited.net/siteexec/content.cgi?page=fv)
![1]

[1]: https://a.fsdn.com/con/app/proj/fileverifier/screenshots/164947.jpg
[2]: http://skwire.dcmembers.com/apps/sfv_ninja/img/main.png
[3]: http://www.freewarefiles.com/screenshot/multihasher.jpg

**Comment by vatterspun** [comment]
So the expected behavior is to make the stop/cancel button end hashing but keep all the hashes generated so far?

I can see either a "pause" or "work in background" button being useful for when you need all your computer resources for something else.

Should also note that RapidCRC is far in advance of MultiHasher.

**Comment by OV2** [comment]
RCRC only has a pause button at the moment. I can see the use of a stop button, but at the moment the design does not support this. When I get back to work on it I'll try to take it into consideration.

**Comment by sergeevabc** [comment]
Is there anything a mere user like me could do to expedite a resolution of this issue?

**Comment by OV2** [comment]
Unless you can somehow give me more free time, not really.

I added a stop button in 0.3.21

**Comment by sergeevabc** [comment]
Thank you, @OV2.
