### ISSUE TITLE
Feature request: change taskbar progress display behaviour

### ISSUE THREAD

**Issue by bejita7** [OV2/RapidCRC-Unicode#41]
It would be much better if progress display on taskbar showed overall progress instead of current file progress. With many files this isn't helpful at all.
![2016-12-28 22-33](https://cloud.githubusercontent.com/assets/2895218/21532469/c1044882-cd50-11e6-8b8b-1b425c311e5c.gif)

**Comment by OV2** [comment]
That's what it was supposed to do, thanks for the hint. I've fixed it with 0.3.22.
