### ISSUE TITLE
any chance of cli support?

### ISSUE THREAD

**Issue by rhazor** [OV2/RapidCRC-Unicode#48]
to run in batch files. or maybe can recommend cli create sfv alternatives? that are not 10 years old outdated.

**Comment by vatterspun** [comment]
I was sure I'd be able to find something with minimal searching, but I had a really hard time with this.  I was going to suggest QuickHash GUI but I couldn't seem to find the tools underneath Quickhash (it's evidently all built into a single executable).  As such, I'd probably start with Cygwin as it's a catalog of Linux tools (including hashing) that is actively updated.

**Comment by rhazor** [comment]
It's OK found alternatives.

**Comment by OV2** [comment]
It would be nice, but at the moment RCRC is not designed for operating in a cli way.
