### ISSUE TITLE
Create one checksum file for every job

### ISSUE THREAD

**Issue by MrDito** [OV2/RapidCRC-Unicode#51]
When you activate the option "Enable Job Queueing" you can save time by processing multiple bunches of files in successive jobs.
For this mode, it would be nice to have an additional option in the "How to create the checksum file(s)"-window which allows to create one checksum file for every job (stored in the overlying directory).

**Comment by OV2** [comment]
I'll try to add this in the next version.

**Comment by MrDito** [comment]
Very cool, thank you very much.

**Comment by OV2** [comment]
Finally had the time to add this. The only problem is when you have multiple jobs in the same directory and use an automatic name then both jobs get the same filename and the later one overwrites the first.

**Comment by MrDito** [comment]
Thank you for adding this feature! Nice to see continuous extensions and improvements to this great program.
Concerning the duplicated filenames for jobs with the same job-root-directory, maybe you could just use some kind of auto-renaming by adding a suffix like <filename>_2? Otherwise, the user needs to become informed to prevent confusion.
