### ISSUE TITLE
error in hash file of multiple files (jobs) from different directories in the same drive (eg C:\)

### ISSUE THREAD

**Issue by almotawahich55000** [OV2/RapidCRC-Unicode#52]
when i want to create one hash file for multiple files from different directories in the C:\ 
(for example from C:\users\sami\test\folder1 and C:\users\sami\folder2)
drive, the saved hash file has problem because paths of files aren't absolut. But when 
i add a file (job) from different drive (e.g. D:\ E:\) to the list of files  then i save the hash file, the hash became good (because it contain absolut paths)

please, can you add option for making hashes with absolut paths

**Comment by OV2** [comment]
When you select multiple jobs/files from different jobs and create a hash file it will search for the last common directory and make the saved paths relative from there. So in your case the common root would be C:\users\sami

An option for absolute paths has already been added in 0.3.20
