### ISSUE TITLE
Info about the "Open with reparent" shell extension entry 

### ISSUE THREAD

**Issue by darkred** [OV2/RapidCRC-Unicode#54]
What is the difference between the following shell extension menu entries (especially the 2nd one)? 
`Open`, 
`Open with reparent` and 
`Open all hashes` 

PS. Sorry for making an issue post for asking about documentation,
but I couldn't find any relevant info.

**Comment by OV2** [comment]
Those entries are also available in the open dialog (dropdown arrow on open button) or when dragging files onto the main window with the right mouse button.

- _Open_ is regular open (hash normal files, or if the first file is a hash file then open this).
- _Open with reparent_ will allow you to open a hash file and select the root folder from where relative paths in the hash file are resolved (for example you have a sfv file on your harddisk and want to compare files on a cd to it).
- _Open all hashes_ will take what you selected or dropped, recursively take all hash files it finds and hash them all as individual jobs (only makes sense with job queue enabled).

**Comment by darkred** [comment]
Thank you for the detailed reply.
