### ISSUE TITLE
Drag and drop of more than one sfv, md5, sha... file without modifier key or right mouse button option

### ISSUE THREAD

**Issue by Cpuroast** [OV2/RapidCRC-Unicode#56]
Can there be an option, so that a modifier key or the right mouse button doesn't have to be used to perform this action?

I often use rapidcrc-unicode on macOS using Wine and it doesn't handle ctrl dragging or right mouse button dragging to the rapid-crc window. I haven't found a native mac application that even comes close to RapidCRC-Unicode.

The other simpler possibility would be to make it the default behaviour, without an option, I think most people that drag/drop multiple checksum files(sfv, md5, sha, etc) to the rapidcrc window expect all of them to be checked, not just one.

**Comment by OV2** [comment]
I still have this on my todo list.

It should be possible to automatically switch to the "Open all hash files" mode if the first dropped file is a hash file.
