### ISSUE TITLE
Selecting multiple sfv, md5, sha... files via the "Open Files" button only checks 1 file

### ISSUE THREAD

**Issue by Cpuroast** [OV2/RapidCRC-Unicode#57]
Selecting multiple sfv, md5, sha... files via the "Open Files" button only checks 1 file.

**Comment by OV2** [comment]
You need to use the dropdown arrow on the open button in the dialog and select "Open all hash files"

**Comment by Cpuroast** [comment]
ah, in Wine, that dropdown arrow doesn't appear, could be some legacy dialog window still left in the code:

![rapidcrc-unicode-open-window](https://user-images.githubusercontent.com/3321892/28725852-cdd16454-738c-11e7-990b-3a92ed398aca.png)

**Comment by OV2** [comment]
The new dialog only appears in vista and up (OsVersion >=6.0). Wine probably reports an older version and does not support the new dialog.
