### ISSUE TITLE
Missing files?  Can't compile.

### ISSUE THREAD

**Issue by DroidSparks** [OV2/RapidCRC-Unicode#58]
In https://github.com/OV2/RapidCRC-Unicode/blob/c5193632cce25f05b28f0885a802875553dab7bb/threadprocs.cpp#L36 there is a file it tries to include, but, it isn't in the repo.

crc32c.h is missing, so, can't compile anything.

**Comment by OV2** [comment]
Sorry for that, just pushed the missing files to the repo.

**Comment by DroidSparks** [comment]
Thanks!

May I ask what version of MSVC you are using?
With Microsoft Visual C++ 2017
It needs this include file in crc32c.cpp for the __cpuid
```
@@ -22,10 +22,11 @@
 #define _CRT_SECURE_NO_WARNINGS
 #endif
 
 #include "crc32c.h"
 #include <nmmintrin.h>
+#include <intrin.h>
 
 #define NOMINMAX
 
 #include <algorithm>
 
 ```

but it still has this issue...
```
1>e:\rapidcrc-unicode\md4.cpp(31): error C2248: 'CMD4::MD4State': cannot access private struct declared in class 'CMD4'
1>e:\rapidcrc-unicode\md4.h(48): note: see declaration of 'CMD4::MD4State'
1>e:\rapidcrc-unicode\md4.h(28): note: see declaration of 'CM
```
...
and once that is fixed, it is missing this file:
`RapidCRC.rc(10): fatal error RC1015: cannot open include file 'afxres.h`

**Comment by OV2** [comment]
I'm building with MSVC 2008 and WinSDK 7.1.
You can probably remove the afxres.h reference, it should not be needed.
