### ISSUE TITLE
Don't re-list files at the end of the list after calculating hashes

### ISSUE THREAD

**Issue by aaaxx** [OV2/RapidCRC-Unicode#60]
The current behaviour is unintuitive, pointless and makes a disorienting mess as soon as you have more than a handful of files or you calculate more than one hash.

Each file should be listed only once, and only have its hash column updated upon calculation.

**Comment by OV2** [comment]
I'm not really sure what you mean. Can you post a step by step list to reproduce the behavior you want changed?

**Comment by aaaxx** [comment]
![storyboard illustrating the behaviour](https://user-images.githubusercontent.com/6186480/36467214-082131e4-16de-11e8-861e-ccaa382f2310.png)

**Comment by OV2** [comment]
This seems to be a bug when job queueing is disabled in the options. I'll look into it.
