### ISSUE TITLE
Options meaning

### ISSUE THREAD

**Issue by agg21** [OV2/RapidCRC-Unicode#64]
Hello, could somebody tell me what does mean options like "open with reparent" and "open all hash files"? What are the differences compared to the normal "open"?

**Comment by OV2** [comment]
"Open with reparent" will ask you for the base folder where the files are located. Usually you have a .sfv/.md5 file and the paths in it are relative to its location. If you've moved the hash file (or the target files) to a different location you can open it with this option and specify where they are located.

"Open all hash files" will recursively go through the directory and open all hash files in verify mode. This really only makes sense if you've enabled job queueing.
