### ISSUE TITLE
RapidCRC usage example

### ISSUE THREAD

**Issue by vatterspun** [OV2/RapidCRC-Unicode#65]
There are many, many uses for this program and certainly it's the most flexible and intelligent hashing program I've come across.  Still, I thought it might be interesting to hear about its use by one of its active users.  This might be useful in terms of explaining the program or maybe in a helpfile someday, who knows?

This is my system:

1. Create a backup of a folder on my desktop with all my critical information by run 7zip and compressing the data. I have it configured to update an existing 7z file.

2. Save the .7z file to an external drive while it auto-uploads to a remote server (the 7zip programs’ output is to the root of my cloud service folder)

3. I run RapidCRC Unicode on the file and click “CRC into Filename”. This has the dual role of letting me use the same file name many times on the drive and check later that the files haven’t corrupted either on my remote site or my external media (it gets saved to two places).

4. Copy the file to the external drive (since it’s important to hash BEFORE transfer, otherwise you just have a unique hash for a broken file)

5. Here’s what I see at the end of the process:

![1](https://user-images.githubusercontent.com/1289134/56707877-5538bd00-66e0-11e9-81e2-748efc75f4c5.png)

6. I try to recheck at least one of the previous backups to check that the drive is working okay and the process is still effective.

Notes:

* I know I could do differential backups and probably save a lot of extra space here, but I like to cycle out old backups and I’m not quite sure how to do that in 7zip.

* As this is a backup, I know it would be better to add parity via a program like MultiPar to better protect the data, but since it’s stored in two places I’m not super worried.

Feedback on this process or examples of how you use the program are welcome.  This is not an problem with the software so feel free to close the issue.

**Comment by rescenic** [comment]
Nice guide. Thanks.
