### ISSUE TITLE
Add file list

### ISSUE THREAD

**Issue by ghost** [OV2/RapidCRC-Unicode#70]
Hello I use RapidCRC Unicode 0.3.31.0 - http://dl.ov2.eu/programs/rapidcrc-unicode/rapidcrc_0.3.31_x64.rar

I'm missing a special option when users drag and drop a 2TB folder into the system, for example, it doesn't hash immediately. Instead the files are displayed in a file list.

The user should then have the option to select the files from the file list or not.

The selected files will then be hashed.

**Comment by f6zhdkw6** [comment]
The advantage of this option is that you can extend it a lot, for example through the file list the users can also pause or cancel the hash process. 

and can save the already hashed files that are mark in the file list as checksum files.

as long as the user has not quit the software, the other files in the file list that have not yet been hashed can continue the hash process.

**Comment by OV2** [comment]
This does not really fit in the current way rapidcrc works, so it will probably not happen.
