### ISSUE TITLE
Menu options don't stick

### ISSUE THREAD

**Issue by danielmmmm** [OV2/RapidCRC-Unicode#71]
Best hashing program out there :-)

Only the menu options don't stick. Whenever I unmark e.g. "Open with reparent" or other entries and confirm by clicking "OK", nothing changes. The menu keeps showing all entries. I tried running RapidCRC as admin, without a difference.

**Comment by OV2** [comment]
Thanks for reporting. I think I've found the problem, will try to build a new version this weekend.
Until then you can try creating the registry key "HKEY_CURRENT_USER\Software\RapidCRC", after that it should start working.

**Comment by danielmmmm** [comment]
Worked perfectly well, thanks a lot!
