### ISSUE TITLE
Windows 2000 (win2k) build

### ISSUE THREAD

**Issue by davidmbesonen** [OV2/RapidCRC-Unicode#72]
How much work would it be to build RapidCRC-Unicode for Windows 2000?

I still touch win2k once in a while and would prefer to have access to the most recent RapidCRC-Unicode version on that OS too.

**Comment by OV2** [comment]
It still builds fine with the old visual studio, sha3 was simply way faster when built with the new studio. 
I'll do a build for the small bugfix version hopefully out this evening, but I'm not sure I want to do this for every release.

**Comment by OV2** [comment]
There is a build up for 0.3.32 now.
