### ISSUE TITLE
[Feature request] "Favorite" hash action

### ISSUE THREAD

**Issue by vatterspun** [OV2/RapidCRC-Unicode#73]
So this isn't a request for anything new, just a little automation to quickly process actions already available within RapidCRC Unicode.

**Background:** 

This program has a lot of smart features and functionality, but at least 9 times out of 10 I'm really using it for one thing.  In my case, it's putting CRC32 values into the filename.  As such, I got the idea to just pick one action and have that run automatically when executed.

**Current behavior:**

When you drag-and-drop a file or folder onto the program or use the "Send To" menu in Windows, it hashes the file using the selected algorithms.

![explorer_EmUUU0Skt8](https://user-images.githubusercontent.com/1289134/81487213-a3a3f580-9228-11ea-84b3-2a6f05fdaa1f.png)

You can then pick one and copy it to your clipboard, generate a hash file, add the CRC32 value to the filename, etc.

**Requested behavior:**

In options, the ability to enable/disable the "favorite" function where a selected algorithm and output, maybe with a quick popup saying what's happened, and then either minimize or auto-close the program.  Example actions:

* Put the CRC32 hash into the filename (my favorite) 
* Copy the SHA256 value to your clipboard (important for security people)
* Generate a Blake2sp file 

---

I can mockup something on this if that's useful or interesting.

Note that an additional "are you sure?" prompt might make sense for some users to avoid renaming a lot of files if you forgot the favorites setting.  Or just go with the standard prompt:

![RapidCRC_2FFSTTCnbw](https://user-images.githubusercontent.com/1289134/81487336-bec33500-9229-11ea-9a23-a1052df121b9.png)

**Comment by OV2** [comment]
Doesn't the shell extension offer most of this (without the auto-close)?

**Comment by vatterspun** [comment]
Oh I didn't know that -- I only use the portable version.  I'll setup the installer version and see.

**Comment by vatterspun** [comment]
I just got the installer version online and, yes it does two of the three mentioned:

* Copy the SHA256 value to your clipboard (important for security people)
* Generate a Blake2sp file

However: 

1. No current option to copy straight to the clipboard.
2. This require admin, some systems can't install programs so the portable software is ideal.

---

I can update the case to reflect this,, create another case that covers it better, or I can close the issue if this doesn't sound worthwhile.

**Comment by vatterspun** [comment]
I'll go ahead and close this issue -- if you'd like me to clarify or resubit, please let me know.  Rather not take up space versus other, more interesting issues.
