### ISSUE TITLE
Binary download over HTTPS not possible

### ISSUE THREAD

**Issue by beerisgood** [OV2/RapidCRC-Unicode#74]
e.g.
`https://dl.ov2.eu/programs/rapidcrc-unicode/RapidCRC-Setup-0.3.33-x64.msi`

SSL Report: dl.ov2.eu (185.44.107.200):
Certificate name mismatch
https://www.ssllabs.com/ssltest/analyze.html?d=dl.ov2.eu
Also:
**Overall Rating: T**

Chromium-Edge also show me:
NET::ERR_CERT_COMMON_NAME_INVALID

So why not just upload the files at GitHub ?
Then their is no need to use insecure external server

**Comment by OV2** [comment]
I've enabled https.

**Comment by beerisgood** [comment]
Now you need to change the download links for your binary's to the HTTPS version as all still linked to HTTP

**Comment by beerisgood** [comment]
@OV2

**Comment by tERyceNzAchE** [comment]
New download links still are not https.

**Comment by OV2** [comment]
I've changed the newest links to https
