### ISSUE TITLE
[Feature Request] Add BLAKE3 Support

### ISSUE THREAD

**Issue by tERyceNzAchE** [OV2/RapidCRC-Unicode#79]
Please add support for [BLAKE3](https://github.com/BLAKE3-team/BLAKE3) with the extension `.blake3` (for compatibility with other programs).

Support both BLAKE3-256 and BLAKE3-512, default of BLAKE3-256 (for .blake3) but ideally support both with same file extension and determine which based on the hash length in the file.

**Comment by tERyceNzAchE** [comment]
Thank you for implementing this so quickly!

**Comment by OV2** [comment]
For now I've added the predefined 32bit blake3 hash length in .blake3 files. So far I haven't seen blake3-512 used anywhere.

**Comment by tERyceNzAchE** [comment]
> So far I haven't seen blake3-512 used anywhere.

That will change once there is an easy way to generate blake3-512 on Windows.  It is used quite a bit since the b3sum (official BLAKE3 implementation) can generate them easily with a command line option.

**Comment by vatterspun** [comment]
> For now I've added the predefined 32bit blake3 hash length in .blake3 files

Thanks.  Tested on a 4TB drive to hash it's contents and it worked great.

**Comment by g0blin-NN** [comment]
> easily with a command line option (-l 64).

what to check? `b3sum` itself cannot. only 32. [here](https://github.com/BLAKE3-team/BLAKE3/issues/208#issuecomment-963384710)
