### ISSUE TITLE
Filename with symbols not being found during verification

### ISSUE THREAD

**Issue by tERyceNzAchE** [OV2/RapidCRC-Unicode#87]
Filename: `11. ✓ CHALLENGE 1-2 - let, var and closures - SOLUTION.mp4`

RapidCRC correctly hashes the file and stores the correct filename, however on verify it reads the filename as: `11. âœ“ CHALLENGE 1-2 - let, var and closures - SOLUTION.mp4` and shows it as file not found.

This is on Windows 10 Pro (x64) with RapidCRC-Unicode 0.3.36.

**Comment by OV2** [comment]
This is a problem of the codepage autodetection. It cannot correcty determine that this is utf8 from the text the hash file contains.
You can fix it by configuring rcrc to read utf8 by default:
![image](https://user-images.githubusercontent.com/415729/113514925-97780380-9571-11eb-84ca-5031aa47d763.png)

The other option is to create hash files as UTF16, which contain a header that does not require auto detection.

**Comment by tERyceNzAchE** [comment]
On a Windows 10 system, why not assume UTF-8 as default?  Even Notepad uses UTF-8 without BOM as the default.

**Comment by OV2** [comment]
Notepad uses a better auto-detect algorithm that correctly determines UTF8. I might look into using a different algorithm if I find the time.

The setting does not default to utf8 to allow old hash files to work correctly, but it has been so long that I might simply change this for the next release.

**Comment by tERyceNzAchE** [comment]
Are old hash files ASCII?

**Comment by OV2** [comment]
Old hash files were usually created in the codepage of the system they were created on, for example windows-1252 for western europe. Without the auto-detect these will be opened as utf8 and produce similar problems if they contain non-ascii characters.

But as I said, I'll probably just make utf8 the default and let those that encounter issues turn the auto detect back on.
