### ISSUE TITLE
Option to Put Other Checksums in Name?

### ISSUE THREAD

**Issue by BarrorL** [OV2/RapidCRC-Unicode#88]
Like "CRC into Filename", perhaps putting other checksums into filename could be an additional option? Windows does have a character limit for filenames, but maybe adding a feature for shorter ones like MD5 could be nice.

**Comment by OV2** [comment]
This is already possible: you can right click the "CRC into Filename" button and you will get a popup menu with the other hashes.

(If you were the one that sent me a similar email request: I was unfortunately unable to answer since outlook.com has ov2.eu on one of their blacklists)

**Comment by BarrorL** [comment]
> This is already possible: you can right click the "CRC into Filename" button and you will get a popup menu with the other hashes.
> 
> (If you were the one that sent me a similar email request: I was unfortunately unable to answer since outlook.com has ov2.eu on one of their blacklists)

Yes, but could you add an option to put other checksums into file name?

**Comment by BarrorL** [comment]
Ah, I see what you mean. Thanks!
