### ISSUE TITLE
File not found when opening a .sha512 file containing uncommon filename characters

### ISSUE THREAD

**Issue by comanche** [OV2/RapidCRC-Unicode#90]
RapidCRC version 0.3.36.0.

Getting a "File not found" in the **Info** column when opening a `.sha512` file containing uncommon filename characters.

Steps to Reproduce (this was tested on `D:` but you may use any other drive):

1. Create directory `D:\s\k\m\b\AAA - MMM oo ttt SSSS - 1`.
2. Inside `D:\s\k\m\b\AAA - MMM oo ttt SSSS - 1`, create a test file called `00 - 00-00 (Test O’Clock).txt` with the contents `foobar`.
3. Drag file `D:\s\k\m\b\AAA - MMM oo ttt SSSS - 1\00 - 00-00 (Test O’Clock).txt` into RapidCRC.
4. Click on **SHA** and select **SHA512**.
5. Check on `Save absolute paths`.
6. Click on **OK** to save the `.sha512` file.
7. Open the saved file `.sha512` file back in RapidCRC.
8. The **Info** column will show "File not found".
9. Change the curly single quote `’` in the file name to a straight single quote `'`.
10. Repeat steps 4-5.
11. The **Info** column will show "File OK".

**Comment by OV2** [comment]
I can't reproduce this - maybe your problem is #87 ?
